spring.application.name=constructerApp

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/adil_construction
# spring.datasource.username=postgres
# spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Batch insert optimization (for saveAll in notifications broadcast)
spring.jpa.properties.hibernate.jdbc.batch_size=20

jwt.secret=gsdyfjyssgfkukyfchghhgdskuyfiubljhlkjhlvvhhhg
jwt.expiration=86400000

# Bootstrap Admin (app start pe ek baar seed hoga agar koi ADMIN na ho)
admin.bootstrap.name=Super Admin
admin.bootstrap.email=admin@constructer.com
admin.bootstrap.password=Admin@1234
admin.bootstrap.phone=9999999999
# Email Configuration (Gmail SMTP Alert)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${kkaif2687@gmail.com}
spring.mail.password=${itxf zpoi lzry nrpo}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin Notification Recipient Email
admin.notification.email=kkaif2687@gmail.com
